blog/urls.py
from django.conf.urls import url
from django.views.generic.list import ListView
from blog import views
from blog.models import About

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'^article/(?P<article_id>\d+)/$',views.ArticleDetailView.as_view(), name = 'detail'),
    url(r'^article/category/(?P<cate_id>\d+)/$', views.CategoryDetailView.as_view(), name = 'cate'),
    url(r'^full/$',views.IndexViewFull.as_view(), name = 'indexFull'),
    url(r'^about/$', ListView.as_view(template_name = 'blog_about.html', model = About), name='about'),
    url(r'^contact/$', ListView.as_view(template_name = 'blog_contact.html',model = About), name='contact'),
    url(r'^contact/send/$', views.setEmail, name = 'send'),
    url(r'^article/(?P<article_id>\d+)/comment/$', views.comment),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('blog.urls', namespace = 'blog', app_name = 'blog')),
    url(r'^finger/', include('finger.urls', namespace = 'finger', app_name = 'finger')),
    url(r'^admin/', admin.site.urls),
]

urls.py
from  django.conf.urls import url
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^test/$',views.test),
]

blog/models.py
from django.db import models
# Create your models here.

class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )
    title = models.CharField('标题', max_length = 70)
    body  = models.TextField('正文')
    create_time = models.DateTimeField('创建时间', auto_now_add = True)
    last_modified_time = models.DateTimeField('修改时间', auto_now = True)
    status = models.CharField('文章状态', max_length = 1, choices = STATUS_CHOICES)
    abstract = models.CharField('摘要', max_length = 154, blank = True, null = True,
                                help_text  = "可选， 如若为空将摘取正文前154个字符")
    views = models.PositiveIntegerField('浏览量', default = 0)
    likes = models.PositiveIntegerField('点赞数', default = 0)
    topped = models.BooleanField('置顶', default = False)
    cateory = models.ForeignKey('Category', verbose_name = '分类',
                                null = True,
                                on_delete = models.SET_NULL)
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-last_modified_time']


class Category(models.Model):
    name = models.CharField('类名', max_length = 20)
    created_time = models.DateTimeField('创建时间', auto_now_add = True)
    last_modefied_time = models.DateTimeField('修改时间', auto_now = True)
    def __str__(self):
        return self.name

class About(models.Model):
    SEX_CHOICES = (
           ('Man', 'Man'),
           ('Women', 'Women'),
          )
    name = models.CharField('姓名', max_length = 20)
    sex = models.CharField('性别', max_length = 5, choices = SEX_CHOICES)
    age  = models.DateField('出生')
    email = models.EmailField('邮箱')
    identity = models.CharField('身份', max_length = 20)  
    say = models.TextField('我说')
   
    def __str__(self):
        return self.name

class Contract(models.Model):
    name = models.CharField('姓名',max_length = 20)
    email = models.EmailField('邮箱')
    subject = models.CharField('主题', max_length = 100)
    message = models.TextField('信息')

class Comment(models.Model):
    article_id = models.ForeignKey('Article',verbose_name='文章',
                                   null = True,
                                   on_delete = models.SET_NULL)
    name = models.CharField('姓名',max_length = 20)
    email = models.EmailField('邮箱')
    message = models.TextField('信息')
    create_time = models.DateTimeField('时间', auto_now_add = True)

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render,render_to_response
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from blog.models import Article, Category, Contract,Comment
import markdown2
import datetime
from django.core.mail import EmailMultiAlternatives,send_mail  
def setEmail(request):
    if request.method == "POST":
        send_mail(request.POST['subject'],
                  request.POST['name']+':         Message: '+request.POST['message'],
                  request.POST['email'], 
                  ['544347795@qq.com',], 
fail_silently=False)
        return HttpResponse(u'发送邮件成功')
    return render_to_response('blog_index.html')

def comment(request,article_id):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        article = Article.objects.get(id = article_id)
        comment = Comment(
                         article_id = article,
                         name = name,
                         email = email,
                         message = message,)
        comment.save()
        send_mail(name+' 评论了你的文章（'+article.__str__()+'）', message, email, ['544347795@qq.com',], fail_silently = False)
        return HttpResponse('ok');
    return HttpResponse('error')

class IndexView(ListView):
    template_name = 'blog_index.html'
    context_object_name = 'article_list'
    def get_queryset(self):
        article_list = Article.objects.filter(status = 'p')
        for article in article_list:
             article.body = markdown2.markdown(article.body, )
        return article_list
    def get_context_data(self, **kwargs):
        date_now = datetime.datetime.now()
        date_ = date_now - datetime.timedelta(days = 7)
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['recent_list']   = Article.objects.filter(status = 'p', last_modified_time__range = (date_, date_now)).order_by('last_modified_time')
        return super(IndexView, self).get_context_data(**kwargs)

class IndexViewFull(ListView):
    template_name = 'blog_indexFull.html'
    context_object_name = 'article_list'
 
    def get_queryset(self):
        article_list = Article.objects.filter(status = 'p')
        for article in article_list:
            article.body = markdown2.markdown(article.body, )
        return article_list
    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        return super(IndexViewFull, self).get_context_data(**kwargs)

class ArticleDetailView(DetailView):
    model = Article
    tempalte_name = 'blog_detail.html'
    context_object_name = 'article'
    pk_url_kwarg = 'article_id'
    
    def get_object(self,**kwargs):
        obj = super(ArticleDetailView, self).get_object()
        obj.views += 1
        obj.save()
        obj.body = markdown2.markdown(obj.body, extras=['fenced-code-blocks'],)
        return obj
    def get_context_data(self, **kwargs):
        kwargs['comment_list'] = Comment.objects.filter(article_id = self.kwargs['article_id']).order_by('create_time')
        return super(ArticleDetailView, self).get_context_data(**kwargs)
class CategoryDetailView(ListView):
      template_name = 'blog_index.html'
      context_object_name = 'article_list'
      def get_queryset(self):
          article_list = Article.objects.filter(cateory_id = self.kwargs['cate_id'],status = 'p')
          for article in article_list:
               article.body = markdown2.markdown(article.body, )
          return article_list
      def get_context_data(self, **kwargs):
          kwargs['category_list'] = Category.objects.all().order_by('name')
          return super(CategoryDetailView, self).get_context_data(**kwargs)

class IndexAdout(ListView):
    template_name = 'blog_about'
    context_object_name = 'aboutme_list'
    
    def get_queryset(self):
        aboutme_list = Article.objects.filter(status = 'p')

blog/templates/blog_about.html
{% extends 'blog_base.html' %}
{% block content %}
  <div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="{{ STATIC_URL }}img/me2.jpg" alt="Developer Image">
                {% for about in object_list %}
                <div  style="position:absolute; z-index:2; left:550px; top:150px">
                     <p><span>Name  &nbsp;&nbsp; &nbsp; &nbsp;{{about.name}}</span></p>
                     <p><span>Sex   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;     {{about.sex}}</span></p>
                     <p><span>Birth &nbsp; &nbsp; &nbsp; &nbsp;     {{about.age}}</span></p>
                     <p><span>Identity &nbsp; &nbsp;  {{about.identity}}</span></p>
                    <p><span>E-mail &nbsp; &nbsp; &nbsp; {{about.email}}</span></p>
                  <h2>&nbsp;</h2> 
                  {{about.say|safe}}
               </div>
                   </figure>
               {% endfor %}
								<div class="height-40px"></div>
								<h2 class="title text-center">-------------</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span >H</span></a></li>
									<li class="twitter"><a href="#"><span ></span>E</a></li>
									<li class="google-plus"><a href="#"><span >L</span></a></li> 
                  <li class="google-plus"><a href="#"><span >L</span></a></li>
									<li class="tumblr"><a href="#"><span >O</span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
{% endblock %}

blog/templates/blog_base.html
<!DOCTYPE html>
<html>
	<head>
	  <title>Blog &amp; EleZt</title>
        <link href="{{ STATIC_URL }}img/code.ico" rel="shortcut icon">
        <!-- meta -->
          <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″>
	  <!-- css -->
	  <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
	  <link rel="stylesheet" href="{{ STATIC_URL }}css/ionicons.min.css">
          <link rel="stylesheet" href="{{ STATIC_URL }}css/pace.css">
	  <link rel="stylesheet" href="{{ STATIC_URL }}css/custom.css">
          <link rel="stylesheet" href="{{ STATIC_URL }}css/github.css">
	  <!-- js -->
	  <script src="{{ STATIC_URL }}js/jquery-2.1.3.min.js"></script>
	  <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
	  <script src="{{ STATIC_URL }}js/pace.min.js"></script>
	  <script src="{{ STATIC_URL }}js/modernizr.custom.js"></script>
          <script src="{{ STATIC_URL }}hitcount/hitcount-jquery.js"></script>
          <script src="{{ STATIC_URL }}hitcount/jquery.postcsrf.js"></script>
	</head>

	<body>
		{% include 'blog_nav.html' %}
                {% block nav %}{% endblock %}
                {% block content %}{% endblock %}
                {% include 'blog_footer.html' %}
		<script src="{{ STATIC_URL }}js/script.js"></script>

	</body>
</html>

blog/templates/blog_contact.html
{% extends 'blog_base.html' %}

{% block content %}
    <div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="send/" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button type = "submit" ><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>


{% endblock%}

blog/templates/blog_detail.html
{% extends 'blog_base.html' %}

{% block content%}
    {{ article.body }}
  
{% endblock%}

blog/templates/blog_footer.html
{% block footer %}
  <!-- Footer -->
  <footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2016 Django1.1  Python3.4.1</p>
					</div>
				</div>
			</div>
		</footer>
{% endblock %}

blog/templates/blog_index.html
{% extends 'blog_base.html' %}
{% block content %}
    <div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
          {% for article in article_list%}
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">{{article.cateory}}</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">{{ article.create_time }}</time></a></span>
			
									<span class="post-author"><a href="#">Elezt</a></span>
			
									<span class="comments-link"><a href="#"> {{  article.views }} views</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>{{ article.abstract }}</p>
								<div class="read-more cl-effect-14">
									<a href="{% url 'blog:detail' article.pk %}" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>
          {% endfor %}
					</main>
					<aside class="col-md-4">
						<div class="widget widget-recent-posts">		
							<h3 class="widget-title">Recent Posts</h3>
              <ul>		
              {% for recent in recent_list %}
								<li>
									<a href="{% url 'blog:detail' recent.pk %}">{{ recent.title }}</a>
								</li>
              {% endfor %}
							</ul>
						</div>
						<div class="widget widget-archives">		
							<h3 class="widget-title">Archives</h3>		
							<ul>
								<li>
									<a href="#">November 2014</a>
								</li>
								<li>
									<a href="#">September 2014</a>
								</li>
								<li>
									<a href="#">January 2013</a>
								</li>
							</ul>
						</div>

						<div class="widget widget-category">		
							<h3 class="widget-title">Category</h3>		
							<ul>
              {% for cate in category_list %}
								<li>
									<a href="/article/category/{{ forloop.counter }}">{{ cate.name }}</a>
								</li>
              {% endfor %}
							</ul>
						</div>
					</aside>
				</div>
			</div>
		</div>

    {% for article in article_list%}
	  {% endfor %}
{% endblock %}

blog/templates/blog_indexFull.html
<!-- full width-->
 {% extends 'blog_base.html' %}
 {% block content %}
      <div class="content-body">
       <div class="container">
         <div class="row">
         {% for article in article_list%}
            <article class="post post-1">
            <header class="entry-header">
               <h1 class="entry-title">
                 <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
               </h1>
                 <div class="entry-meta">
                   <span class="post-category"><a href="#">{{article.cateory}}</a></span>
 
                   <span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">{{ article.create_time }}</time></a></span>
 
                   <span class="post-author"><a href="#">Elezt</a></span>
 
                   <span class="comments-link"><a href="#">4 Comments</a></span>
                </div>
            </header>
              <div class="entry-content clearfix">
                <p>{{ article.abstract }}</p>
                <div class="read-more cl-effect-14">
                  <a href=" {% url 'blog:detail' article.pk %}" class="more-link">Continue reading <span class="meta-nav">→</span></a>
                </div>
              </div>
            </article>
        {% endfor %}
 {% endblock %}

blog/templates/blog_nav.html
{% block nav %}
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="{{STATIC_URL}}hitcount/hitcount-jquery.js"></script>
    <!-- Blog-nav -->
    <div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' %}"><b>Blog</b> &amp; EleZt</a></h1>
</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:indexFull' %}" data-hover="Blog">Blog</a></li>
                                                                <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:contact'%}" data-hover="Contact">Contact</a></li>
  								<li class="cl-effect-11"><a href="/admin/" data-hover="Admin">Admin</a></li>
                                                                </ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
{% endblock %}